---
title: "Algorithm Sketch"
author: "Ugur Yildirim"
date: "11/22/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Initialization Step

1) Check that:

    - $D$ is connected
    - $g(x)$ is continuous and differentiable everywhere in $D$
    - $h(x) = ln(g(x))$ is concave everywhere in $D$

2) Initialize `T_k` (vector with $k$ elements):

    - $T_k = \{x_i; i = 1, ..., k\}$, where $x_1 \leq ... \leq x_k$ are the $k$ abscissae in $D$ where we will evaluate $h(x)$ and $h'(x)$
    - If $D$ unbounded on the left, chose $x_1$ s.t. $h'(x_1) > 0$
    - If $D$ unbounded on the right, chose $x_k$ s.t. $h'(x_k) < 0$
  
3) Evaluate $h(x)$ and $h'(x)$ on $T_k$ and store these as two length $k$ vectors, say `h_x` and `h_prime_x`

4) Calculate `z` (vector with $k+1$ elements):

    - $z_0$ = lower bound of $D$ (or $-\infty$ if $D$ is not bounded below)
    - For $j = 1, ..., k-1$, $z_j = \frac{h(x_{j+1}) - h(x_j) - x_{j+1} h'(x_{j+1}) + x_j h'(x_j)}{h'(x_j) - h'(x_{j+1})}$ (these are the points at which the tangents to $h(x)$ at $x_j$ and $x_{j+1}$ intersect)
    - $z_k$ = upper bound of $D$ (or $+\infty$ if $D$ is not bounded above)

5) Find `u_k` (this is the piecewise linear upper hull formed by tangents to $h(x)$ at $T_k$):

    - $u_k(x) = h(x_j) + (x - x_j) h'(x_j)$, where $x \in [z_{j-1}, z_j]$ and $j = 1, ..., k$
    - NB: $exp(u_k(x))$ is the rejection envelope on $T_k$

6) Find `s_k`:

    - $s_k(x) = \frac{exp(u_k(x))}{\int_D exp(u_k(x')) dx'}$
    
7) Find `l_k` (this is the piecewise linear lower hull formed by connecting adjacent points on $h(x)$ where $T_k$ is evaluated)

    - $l_k(x) = \frac{(x_{j+1} - x) h(x_j) + (x - x_j) h(x_{j+1})}{x_{j+1} - x_j}$, where $x \in [x_j, x_{j+1}]$ and $j = 1, ..., k-1$
    - For $x < x_1$ or $x > x_k$, define $l_k(x) = -\infty$
    - NB: $exp(l_k(x))$ is the squezzing function on $T_k$

# Sampling Step

1) Sample a value $x^*$ from $s_k(x)$

2) Sample a value $w$ independently from $Unif(0,1)$

3) Perform the test:

    - If $w \leq exp\{l_k(x^*) - u_k(x^*)\}$:
        - Accept $x^*$
    - Else:
        - Evaluate $h(x^*)$ and $h'(x^*)$
        - If $w \leq h(x^*) - u_k(x^*)\}$:
            - Accept $x^*$
        - Else:
            - Reject $x^*$
            
# Updating Step

1) Follow this recipe:

    - If $h(x^*)$ and $h'(x^*)$ were evaluated in Sampling Step:
        - Include $x^*$ in $T_k$ to form $T_{k+1}$
        - Relabel the $x_i$ in $T_k$ in ascending order
        - Construct new functions $u_{k+1}(x)$, $s_{k+1}(x)$, and $l_{k+1}(x)$
        - Increment $k$
        - Return to Sampling Step if $n$ points have not been sampled yet
    - Else:
        - No update necessary, repeat Sampling Step if $n$ points have not been sampled yet
